In [1]:
import numpy as np

In [13]:
x = np.array([[ 0,  1,  2],
           [ 3,  4,  5],
           [ 6,  7,  8],
            [ 9, 10, 11]])
rows = np.array([[0, 0],
                 [3, 3]], dtype=np.intp)
columns = np.array([[0, 2],
                    [0, 2]], dtype=np.intp)
rows

array([[0, 0],
       [3, 3]])

In [14]:
x[1,[1,2]]

array([4, 5])

In [15]:
x[rows,columns]

array([[ 0,  2],
       [ 9, 11]])

In [19]:
rows = np.array([0, 3], dtype=np.intp)
columns = np.array([0, 2], dtype=np.intp)
rows[:, np.newaxis]

x[rows[:, np.newaxis], columns]

x[np.ix_(rows,columns)]

array([[ 0,  2],
       [ 9, 11]])

In [20]:
x = np.array([[0, 1], [1, 1], [2, 2]])
rowsum = x.sum(-1)


array([1, 2, 4])

In [21]:
rowsum = x.sum(-1, keepdims=True)
rowsum

array([[1],
       [2],
       [4]])

In [23]:
rowsum<2

array([[ True],
       [False],
       [False]])

In [24]:
rowsum.shape

(3, 1)